import type {
  AgreementReference,
  Approval,
  ApprovalAction,
  BillingReference,
  ClientRequest,
  Company,
  CompanyMembership,
  CompanyService,
  FileAsset,
  IntegrationConnection,
  Invite,
  Location,
  OnboardingInstance,
  OnboardingStep,
  OnboardingStepTemplate,
  Profile,
  Questionnaire,
  QuestionnaireQuestion,
  QuestionnaireResponse,
  QuestionnaireResponseHistory,
  ReportingMetric,
  Service,
} from "@/lib/types/database";

const now = () => new Date().toISOString();

export const DEMO_ADMIN_ID = "11111111-1111-1111-1111-111111111111";
export const DEMO_CLIENT_ID = "22222222-2222-2222-2222-222222222222";
export const DEMO_COMPANY_ID = "33333333-3333-3333-3333-333333333333";
export const DEMO_ONBOARDING_ID = "44444444-4444-4444-4444-444444444444";

export const SERVICES: Service[] = [
  {
    id: "svc-meta",
    key: "meta_ads",
    name: "Meta Ads",
    description: "Facebook and Instagram advertising",
    active: true,
    sort_order: 10,
  },
  {
    id: "svc-google-ads",
    key: "google_ads",
    name: "Google Ads",
    description: "Search and performance advertising",
    active: true,
    sort_order: 20,
  },
  {
    id: "svc-lsa",
    key: "google_lsa",
    name: "Google Local Services Ads",
    description: "Local services lead ads",
    active: true,
    sort_order: 30,
  },
  {
    id: "svc-seo",
    key: "seo",
    name: "SEO",
    description: "Search engine optimization",
    active: true,
    sort_order: 40,
  },
  {
    id: "svc-geo",
    key: "geo",
    name: "GEO",
    description: "Generative engine optimization",
    active: true,
    sort_order: 50,
  },
  {
    id: "svc-gbp",
    key: "google_business_profile",
    name: "Google Business Profile",
    description: "GBP management and optimization",
    active: true,
    sort_order: 60,
  },
  {
    id: "svc-website",
    key: "website",
    name: "Website",
    description: "Website build or access for marketing work",
    active: true,
    sort_order: 70,
  },
  {
    id: "svc-podcast",
    key: "podcast_editing",
    name: "Podcast Editing",
    description: "Podcast production and editing",
    active: true,
    sort_order: 80,
  },
];

export const TEMPLATES: OnboardingStepTemplate[] = [
  {
    id: "tpl-welcome",
    name: "welcome",
    default_title: "Welcome",
    default_description:
      "Welcome to OnboardBox. We'll walk you through everything JMCG needs to get started. Your progress saves automatically.",
    default_step_type: "instruction",
    default_required: true,
    default_blocks_launch: false,
    service_id: null,
    instructional_video_url: null,
    external_url: null,
    sort_order: 10,
    active: true,
  },
  {
    id: "tpl-company",
    name: "company_info",
    default_title: "Company Information",
    default_description: "Confirm company details JMCG will use across services.",
    default_step_type: "questionnaire",
    default_required: true,
    default_blocks_launch: true,
    service_id: null,
    instructional_video_url: null,
    external_url: null,
    sort_order: 20,
    active: true,
  },
  {
    id: "tpl-agreement",
    name: "agreement",
    default_title: "Review & Sign Agreement",
    default_description: "Review and sign your JMCG agreement in DocuSign.",
    default_step_type: "agreement",
    default_required: true,
    default_blocks_launch: true,
    service_id: null,
    instructional_video_url: null,
    external_url: null,
    sort_order: 30,
    active: true,
  },
  {
    id: "tpl-payment",
    name: "payment",
    default_title: "Initial Payment",
    default_description: "Complete your initial invoice securely through Stripe.",
    default_step_type: "payment",
    default_required: true,
    default_blocks_launch: true,
    service_id: null,
    instructional_video_url: null,
    external_url: null,
    sort_order: 40,
    active: true,
  },
  {
    id: "tpl-biz",
    name: "business_questionnaire",
    default_title: "Business Questionnaire",
    default_description: "Tell us about your services, offers, and goals.",
    default_step_type: "questionnaire",
    default_required: true,
    default_blocks_launch: true,
    service_id: null,
    instructional_video_url: null,
    external_url: null,
    sort_order: 50,
    active: true,
  },
  {
    id: "tpl-files",
    name: "upload_files",
    default_title: "Upload Brand Assets",
    default_description: "Upload logos, photos, and brand materials.",
    default_step_type: "file_upload",
    default_required: true,
    default_blocks_launch: false,
    service_id: null,
    instructional_video_url: null,
    external_url: null,
    sort_order: 60,
    active: true,
  },
  {
    id: "tpl-website",
    name: "website_access",
    default_title: "Website Access",
    default_description: "Grant JMCG access to your website platform.",
    default_step_type: "website_access",
    default_required: true,
    default_blocks_launch: true,
    service_id: "svc-website",
    instructional_video_url: null,
    external_url: null,
    sort_order: 70,
    active: true,
  },
  {
    id: "tpl-google",
    name: "connect_google",
    default_title: "Connect Google Accounts",
    default_description:
      "Authorize Google Ads, Analytics, Search Console, or GBP as needed.",
    default_step_type: "connection",
    default_required: true,
    default_blocks_launch: true,
    service_id: "svc-google-ads",
    instructional_video_url: null,
    external_url: null,
    sort_order: 80,
    active: true,
  },
  {
    id: "tpl-meta",
    name: "connect_meta",
    default_title: "Connect Meta Ads",
    default_description: "Authorize Meta advertising access for your business.",
    default_step_type: "connection",
    default_required: true,
    default_blocks_launch: true,
    service_id: "svc-meta",
    instructional_video_url: null,
    external_url: null,
    sort_order: 90,
    active: true,
  },
  {
    id: "tpl-review",
    name: "final_review",
    default_title: "Final Review",
    default_description: "Review remaining items before launch.",
    default_step_type: "instruction",
    default_required: true,
    default_blocks_launch: false,
    service_id: null,
    instructional_video_url: null,
    external_url: null,
    sort_order: 100,
    active: true,
  },
];

export function createInitialDemoState() {
  const ts = now();
  const admin: Profile = {
    id: DEMO_ADMIN_ID,
    first_name: "Jordan",
    last_name: "Admin",
    email: "admin@jmcg.demo",
    phone: null,
    user_type: "admin",
    created_at: ts,
    updated_at: ts,
  };
  const client: Profile = {
    id: DEMO_CLIENT_ID,
    first_name: "Casey",
    last_name: "Client",
    email: "casey@acmehvac.demo",
    phone: "555-0100",
    user_type: "client",
    created_at: ts,
    updated_at: ts,
  };

  const company: Company = {
    id: DEMO_COMPANY_ID,
    name: "Acme HVAC",
    legal_name: "Acme Heating & Cooling LLC",
    website: "https://acmehvac.demo",
    status: "onboarding",
    ready_to_launch: false,
    approvals_enabled: true,
    primary_contact_email: "casey@acmehvac.demo",
    primary_contact_phone: "555-0100",
    notes: "Demo client for local development.",
    created_at: ts,
    updated_at: ts,
  };

  const membership: CompanyMembership = {
    id: "mem-1",
    company_id: DEMO_COMPANY_ID,
    user_id: DEMO_CLIENT_ID,
    membership_status: "active",
    created_at: ts,
  };

  const locations: Location[] = [
    {
      id: "loc-1",
      company_id: DEMO_COMPANY_ID,
      name: "Main Office",
      address_line1: "100 Main St",
      address_line2: null,
      city: "Austin",
      state: "TX",
      postal_code: "78701",
      country: "US",
      phone: "555-0100",
      website: "https://acmehvac.demo",
      service_area_notes: "Austin metro",
      is_primary: true,
      created_at: ts,
      updated_at: ts,
    },
  ];

  const companyServices: CompanyService[] = [
    {
      id: "cs-1",
      company_id: DEMO_COMPANY_ID,
      service_id: "svc-meta",
      status: "active",
      start_date: null,
      end_date: null,
      notes: null,
      created_at: ts,
    },
    {
      id: "cs-2",
      company_id: DEMO_COMPANY_ID,
      service_id: "svc-google-ads",
      status: "active",
      start_date: null,
      end_date: null,
      notes: null,
      created_at: ts,
    },
    {
      id: "cs-3",
      company_id: DEMO_COMPANY_ID,
      service_id: "svc-website",
      status: "active",
      start_date: null,
      end_date: null,
      notes: null,
      created_at: ts,
    },
    {
      id: "cs-4",
      company_id: DEMO_COMPANY_ID,
      service_id: "svc-seo",
      status: "active",
      start_date: null,
      end_date: null,
      notes: null,
      created_at: ts,
    },
  ];

  const onboarding: OnboardingInstance = {
    id: DEMO_ONBOARDING_ID,
    company_id: DEMO_COMPANY_ID,
    status: "in_progress",
    completion_percentage: 20,
    ready_to_launch: false,
    started_at: ts,
    completed_at: null,
    created_at: ts,
    updated_at: ts,
  };

  const steps: OnboardingStep[] = TEMPLATES.map((tpl, index) => ({
    id: `step-${index + 1}`,
    onboarding_id: DEMO_ONBOARDING_ID,
    company_id: DEMO_COMPANY_ID,
    template_id: tpl.id,
    service_id: tpl.service_id,
    title: tpl.default_title,
    description: tpl.default_description,
    step_type: tpl.default_step_type,
    sort_order: tpl.sort_order,
    required: tpl.default_required,
    blocks_launch: tpl.default_blocks_launch,
    depends_on_step_id: null,
    status: index === 0 ? "completed" : "not_started",
    instructional_video_url: tpl.instructional_video_url,
    external_url: tpl.external_url,
    website_platform: null,
    metadata:
      tpl.name === "connect_google"
        ? { providers: ["google_ads"] }
        : tpl.name === "connect_meta"
          ? { providers: ["meta_ads"] }
          : {},
    completed_at: index === 0 ? ts : null,
    completed_by_user_id: index === 0 ? DEMO_CLIENT_ID : null,
    verified_at: null,
    verified_by_admin_id: null,
    created_at: ts,
    updated_at: ts,
  }));

  const questionnaire: Questionnaire = {
    id: "q-biz",
    onboarding_step_id: "step-5",
    company_id: DEMO_COMPANY_ID,
    name: "Business Questionnaire",
    version: 1,
    status: "active",
    created_at: ts,
  };

  const companyQuestionnaire: Questionnaire = {
    id: "q-company",
    onboarding_step_id: "step-2",
    company_id: DEMO_COMPANY_ID,
    name: "Company Information",
    version: 1,
    status: "active",
    created_at: ts,
  };

  const questions: QuestionnaireQuestion[] = [
    {
      id: "qq-1",
      questionnaire_id: "q-company",
      question_key: "legal_name",
      prompt: "Legal business name",
      help_text: null,
      question_type: "text",
      required: true,
      sort_order: 10,
      configuration_json: {},
    },
    {
      id: "qq-2",
      questionnaire_id: "q-company",
      question_key: "website",
      prompt: "Website URL",
      help_text: null,
      question_type: "text",
      required: true,
      sort_order: 20,
      configuration_json: {},
    },
    {
      id: "qq-3",
      questionnaire_id: "q-company",
      question_key: "primary_phone",
      prompt: "Primary phone",
      help_text: null,
      question_type: "text",
      required: true,
      sort_order: 30,
      configuration_json: {},
    },
    {
      id: "qq-4",
      questionnaire_id: "q-biz",
      question_key: "priority_services",
      prompt: "Which services should we prioritize first?",
      help_text: "List the services that matter most for lead generation.",
      question_type: "textarea",
      required: true,
      sort_order: 10,
      configuration_json: {},
    },
    {
      id: "qq-5",
      questionnaire_id: "q-biz",
      question_key: "service_areas",
      prompt: "Where do you want to generate leads?",
      help_text: null,
      question_type: "textarea",
      required: true,
      sort_order: 20,
      configuration_json: {},
    },
    {
      id: "qq-6",
      questionnaire_id: "q-biz",
      question_key: "monthly_budget",
      prompt: "Approximate monthly marketing budget",
      help_text: null,
      question_type: "text",
      required: false,
      sort_order: 30,
      configuration_json: {},
    },
    {
      id: "qq-7",
      questionnaire_id: "q-biz",
      question_key: "competitors",
      prompt: "Who are your main competitors?",
      help_text: null,
      question_type: "textarea",
      required: false,
      sort_order: 40,
      configuration_json: {},
    },
  ];

  const requests: ClientRequest[] = [
    {
      id: "req-1",
      company_id: DEMO_COMPANY_ID,
      service_id: "svc-meta",
      title: "Upload five recent installation photos",
      instructions:
        "Please upload clear photos from recent jobs we can use in ads.",
      required: true,
      status: "open",
      created_by_admin_id: DEMO_ADMIN_ID,
      completed_by_user_id: null,
      due_date: null,
      created_at: ts,
      completed_at: null,
    },
  ];

  const connections: IntegrationConnection[] = [
    {
      id: "conn-google",
      company_id: DEMO_COMPANY_ID,
      location_id: null,
      provider: "google_ads",
      connection_status: "not_connected",
      external_account_id: null,
      external_account_name: null,
      scopes: [],
      token_reference: null,
      token_expires_at: null,
      last_successful_sync_at: null,
      last_error_code: null,
      last_error_message: null,
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "conn-meta",
      company_id: DEMO_COMPANY_ID,
      location_id: null,
      provider: "meta_ads",
      connection_status: "not_connected",
      external_account_id: null,
      external_account_name: null,
      scopes: [],
      token_reference: null,
      token_expires_at: null,
      last_successful_sync_at: null,
      last_error_code: null,
      last_error_message: null,
      created_at: ts,
      updated_at: ts,
    },
  ];

  const approvals: Approval[] = [
    {
      id: "appr-1",
      company_id: DEMO_COMPANY_ID,
      service_id: "svc-meta",
      title: "Spring AC Tune-Up ad creative",
      description: "Please review the primary image and headline for Meta.",
      item_type: "ad_creative",
      preview_url: null,
      status: "pending",
      created_by_admin_id: DEMO_ADMIN_ID,
      created_at: ts,
      updated_at: ts,
    },
  ];

  const approvalActions: ApprovalAction[] = [];

  const billing: BillingReference[] = [
    {
      id: "bill-1",
      company_id: DEMO_COMPANY_ID,
      provider: "stripe",
      provider_customer_id: "cus_demo_acme",
      provider_invoice_id: "in_demo_initial",
      invoice_type: "initial",
      amount_cents: 250000,
      currency: "usd",
      status: "open",
      due_date: null,
      paid_at: null,
      created_at: ts,
    },
  ];

  const agreements: AgreementReference[] = [
    {
      id: "agr-1",
      company_id: DEMO_COMPANY_ID,
      provider: "docusign",
      provider_envelope_id: "env_demo_acme",
      agreement_name: "JMCG Marketing Services Agreement",
      status: "sent",
      sent_at: ts,
      signed_at: null,
      created_at: ts,
    },
  ];

  const metrics: ReportingMetric[] = [
    {
      id: "m1",
      company_id: DEMO_COMPANY_ID,
      location_id: "loc-1",
      channel: "google_ads",
      metric_name: "spend",
      metric_value: 4200,
      period_start: "2026-07-01",
      period_end: "2026-07-31",
      source: "mock",
      created_at: ts,
    },
    {
      id: "m2",
      company_id: DEMO_COMPANY_ID,
      location_id: "loc-1",
      channel: "google_ads",
      metric_name: "leads",
      metric_value: 48,
      period_start: "2026-07-01",
      period_end: "2026-07-31",
      source: "mock",
      created_at: ts,
    },
    {
      id: "m3",
      company_id: DEMO_COMPANY_ID,
      location_id: "loc-1",
      channel: "meta_ads",
      metric_name: "spend",
      metric_value: 3100,
      period_start: "2026-07-01",
      period_end: "2026-07-31",
      source: "mock",
      created_at: ts,
    },
    {
      id: "m4",
      company_id: DEMO_COMPANY_ID,
      location_id: "loc-1",
      channel: "meta_ads",
      metric_name: "leads",
      metric_value: 36,
      period_start: "2026-07-01",
      period_end: "2026-07-31",
      source: "mock",
      created_at: ts,
    },
    {
      id: "m5",
      company_id: DEMO_COMPANY_ID,
      location_id: "loc-1",
      channel: "seo",
      metric_name: "organic_traffic",
      metric_value: 1820,
      period_start: "2026-07-01",
      period_end: "2026-07-31",
      source: "mock",
      created_at: ts,
    },
    {
      id: "m6",
      company_id: DEMO_COMPANY_ID,
      location_id: "loc-1",
      channel: "google_business_profile",
      metric_name: "calls",
      metric_value: 74,
      period_start: "2026-07-01",
      period_end: "2026-07-31",
      source: "mock",
      created_at: ts,
    },
  ];

  const invites: Invite[] = [];
  const files: FileAsset[] = [];
  const responses: QuestionnaireResponse[] = [];
  const responseHistory: QuestionnaireResponseHistory[] = [];

  return {
    profiles: [admin, client] as Profile[],
    companies: [company] as Company[],
    memberships: [membership] as CompanyMembership[],
    locations,
    services: SERVICES,
    companyServices,
    templates: TEMPLATES,
    onboardings: [onboarding] as OnboardingInstance[],
    steps,
    questionnaires: [questionnaire, companyQuestionnaire] as Questionnaire[],
    questions,
    responses,
    responseHistory,
    requests,
    files,
    invites,
    connections,
    approvals,
    approvalActions,
    billing,
    agreements,
    metrics,
    currentUserId: DEMO_CLIENT_ID as string | null,
    emailLog: [] as Array<{ to: string; subject: string; body: string; at: string }>,
  };
}

export type DemoState = ReturnType<typeof createInitialDemoState>;
